tabvars <- c(
  "num_region",
  # Clinical characteristics
  "num_age",
  "num_age_cat",
  "num_dmgender",
  "num_dmhome",
  "num_dmWeight",
  "num_dmBmi",
  "num_dmBmi_cat",
  "num_dmHF", 
  "d_dmHF_history",
  "d_dmHF_cat",
  "d_HFdiagnosis",
  "num_dmEflp",
  "num_dmEtio",
  "num_dmEtio_c1",
  "num_dmHT",
  "num_dmMi",
  "num_dmPci",
  "num_dmCabg",
  "num_dmValve",
  #"num_dmDev",
  "num_dmDev_cat",
  "num_dmStroke",
  "num_dmAfib_cat2",
  #"num_dmAfib_cat3",
  "num_dmPvd",
  "num_dmVte",
  "num_dmDiab_cat",
  "num_dmHyChol",
  "num_dmCopd",
  "num_dmApn",
  "num_dmHepa",
  "num_dmThy_cat",
  "num_dmDis",
  "num_dmDepr",
  "num_dmSmoking_cat",
  "num_dmAlc", 
  "num_dmPhya", 
  
  # Clinical presentation at hospital admission
  "num_Bpm",
  "num_Bp1",
  "num_Nyha",
  
  "num_Ral", 
  "num_S3", 
  "num_Jvp", 
  "num_Hypop", 
  "num_Eff", 
  "num_Cold", 
  "num_Hep", 
  "num_Mr", 
  "num_Oed", 
  "num_As", 
  
  "d_X_pulmc_alvoedema",
  
  # Laboratory findings
  "num_BunorUre", 
  "num_Urc", 
  "num_Prot",
  "num_Tsh",
  "num_TroporHtrop",
  "num_Trop",
  "num_Hba1",
  "num_Nt",
  "num_Bnp",
  "num_NtorBnp",
  "num_Sod",
  "num_Pot",
  "num_Cre",
  "num_CKDEPI",
  "num_Bun",
  "num_Ure",
  "num_Bili",
  "num_Crp",
  "num_Wbc",
  "num_Hb",

  # ECG
  "num_Ryth_cat",
  "num_Lbbb",
  # Echocardiography
  "num_Ef",
  "num_Lvdd",
  "num_Lvh",
  #"num_EA",
  "num_Edec", 
  "num_LaMes",
  "num_Rsp",
  "num_MitReg",
  "num_AorSte",
  "num_AorReg",
  "num_TriCus",

  # Pharmacotherapy at hospital discharge
  "num_mdDiur",
  "d_mdloopDiur",
  "num_mdAL",
  "d_arb_or_ace_or_arni",
  "num_mdACE",
  "num_mdAT",
  "num_mdARNI",
  "num_mdBB",
  "num_mdCcb",
  "num_mdNit",
  "num_mdIvab",
  "num_mdDigo",
  "num_mdAmi",
  "num_mdAntiar",
  "num_mdAntipl",
  "num_mdAC",
  "num_mdStat"
)

tabdigvars <- c(
  "num_dmhome",
  "num_dmBmi",
  "num_dmHF", 
  "num_dmEtio",
  "num_dmSmoking_cat",
  "num_dmAlc", 
  "num_dmPhya",
  "num_dmApn", 
  "num_dmSpiNoYes", 
  "num_dmEfl", 
  "num_dmEflp", 
  "num_dmEflm", 
  "num_Nyha",
  
  "num_Ral", 
  "num_S3", 
  "num_Jvp", 
  "num_Hypop", 
  "num_Eff", 
  "num_Cold", 
  "num_Hep", 
  "num_Mr", 
  "num_Oed", 
  "num_As", 
  
  "num_BunorUre", 
  "num_Urc",
  "num_Prot", 
  "num_Tsh",
  "num_TroporHtrop",
  "num_Hba1",
  "num_NtorBnp",
  
  "num_Lvdd",
  "num_Lvh",
  #"num_EA",
  "num_Edec", 
  "num_LaMes",
  "num_Rsp",
  "num_MitReg",
  "num_AorSte",
  "num_AorReg",
  "num_TriCus"
)

tabhospvars <- c(  "num_hsHFstat",
                  "num_hsHf",
                  "num_hsAcs",
                  "num_hsFacMy",
                  "num_hsFacNonc",
                  "num_hsFacAf",
                  "num_hsFacVa",
                  "num_hsFacInf",
                  "num_hsFacUnh",
                  "num_hsFacBrad",
                  "num_hsFacRen",
                  "num_hsFacIat",
                  "num_hsFacAne",
                  "num_hsFacOt",
                  "num_hsHosPresCli",
                  "num_hsIntr",
                  "num_hsNitrat",
                  "num_hsProDiu")