```{r kmfunc, cache=cacheon}

kmfunc <- function(time, event, eventname, ymax = 1) {
  efvars <- c("num_Ef_cat", "num_Ef_cat2")

  levs <- c(
    levels(pdata %>% pull(!!sym(efvars[1]))),
    levels(pdata %>% pull(!!sym(efvars[2])))[1:2]
  )
  levsorder <- c(5, 3, 1, 4, 2)
  levsorderorg <- c(1, 2, 3, 1, 2)
  levs2 <- bind_cols(levs = levs, levsorder = levsorder, levsorderorg = levsorderorg) %>%
    mutate(levsprint = str_replace(levs, ">=", "\u2265")) %>%
    arrange(levsorder) %>%
    mutate(
      cols = global_cols[c(3, 1, 1, 2, 2)],
      ltys = c(2, 1, 3, 1, 3)
    )

  fits <- survfit(formula(paste0("Surv(", time, ",", event, "== 1) ~ ", efvars[1])),
    data = pdata %>% filter(survpop)
  )
  ## cox
  smod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "== 1) ~ relevel(", efvars[1], ", ref = '>=50%')")),
    data = pdata %>% filter(survpop)
  ))

  hrprint1 <- paste0(
    fn(smod$conf.int[, 1], dig = 2),
    " (", fn(smod$conf.int[, 3], dig = 2),
    "-", fn(smod$conf.int[, 4], dig = 2), "), ",
    fn(smod$coef[, 5], dig = 3, p = TRUE)
  )

  fits2 <- survfit(formula(paste0("Surv(", time, ",", event, "== 1) ~ ", efvars[2])),
    data = pdata %>% filter(survpop)
  )
  ## cox
  smod2 <- summary(coxph(formula(paste0("Surv(", time, ",", event, "== 1) ~ relevel(", efvars[2], ", ref = '>=50%')")),
    data = pdata %>% filter(survpop)
  ))

  hrprint2 <- paste0(
    fn(smod2$conf.int[1:2, 1], dig = 2),
    " (", fn(smod2$conf.int[1:2, 3], dig = 2),
    "-", fn(smod2$conf.int[1:2, 4], dig = 2), "), ",
    fn(smod2$coef[1:2, 5], dig = 3, p = TRUE)
  )

  hrprint <- tibble(
    hr = c(hrprint1, hrprint2),
    levs = c(
      sub(".*\\)", "", rownames(smod$coefficients)),
      sub(".*\\)", "", rownames(smod2$coefficients)[1:2])
    )
  )

  levs2 <- full_join(levs2, hrprint, by = "levs") %>%
    mutate(hr = ifelse(is.na(hr), "ref", hr))

  # c(bottom, left, top, right)
  cexmy <- 1.2
  par(mar = c(9.75, 8, 1, 1.5) + 0.1)

  plots <- plot(fits,
    fun = "event",
    ylab = paste0(eventname, " (%)"),
    yscale = 100,
    xscale = 30,
    col = levs2 %>% filter(levs %in%
      str_remove_all(names(fits$strata), paste0(efvars[1], "="))) %>% arrange(levsorderorg) %>% pull(cols),
    mark.time = FALSE,
    bty = "n",
    xlim = c(0, 30 * 12),
    ylim = c(0, ymax + 0.05),
    xlab = "Follow-up (months)",
    cex.lab = cexmy,
    axes = F,
    lwd = 2,
    lty = levs2 %>% filter(levs %in%
      str_remove_all(names(fits$strata), paste0(efvars[1], "="))) %>% arrange(levsorderorg) %>% pull(ltys),
    xaxs = "i", yaxs = "i"
  )
  lines(fits2[1:2],
    fun = "event",
    yscale = 100,
    xscale = 365,
    col = levs2 %>% filter(levs %in%
      str_remove_all(names(fits2$strata[1:2]), paste0(efvars[2], "="))) %>% arrange(levsorderorg) %>% pull(cols),
    mark.time = FALSE,
    conf.int = FALSE,
    lwd = 2,
    lty = levs2 %>% filter(levs %in%
      str_remove_all(names(fits2$strata[1:2]), paste0(efvars[2], "="))) %>% arrange(levsorderorg) %>% pull(ltys),
    xaxs = "i", yaxs = "i"
  )

  axis(2, seq(0, ymax + 0.05, 0.05), c(seq(0, ymax * 100, 5), 100), las = 2, cex.axis = cexmy)
  plotrix::axis.break(2, ymax + 0.025, style = "slash")

  seqtime <- seq(0, 12, 2) * 30
  axis(1, at = seqtime, seq(0, 12, 2), cex.axis = cexmy)

  legend(
    x = 0.5, y = ymax + 0.05, bty = "n",
    c("", levs2 %>% pull(levsprint)),
    col = c("white", levs2 %>% pull(cols)), cex = cexmy, lwd = 2, lty = c(1, levs2 %>% pull(ltys)),
    text.col = c("white", levs2 %>% pull(cols))
  )
  legend(
    x = 6 * 30, y = ymax + 0.05, c("HR (95% CI), p-value", levs2 %>% pull(hr)),
    cex = cexmy, adj = 0.5, bty = "n"
  )

  mtext("No. at risk", side = 1, line = 3.7, at = -80, adj = 0, cex = cexmy, font = 2)
  mtext(levs2$levsprint[1], side = 1, line = 4.7, at = -80, adj = 0, cex = cexmy)
  mtext(levs2$levsprint[2], side = 1, line = 5.7, at = -80, adj = 0, cex = cexmy)
  mtext(levs2$levsprint[3], side = 1, line = 6.7, at = -80, adj = 0, cex = cexmy)
  mtext(levs2$levsprint[4], side = 1, line = 7.7, at = -80, adj = 0, cex = cexmy)
  mtext(levs2$levsprint[5], side = 1, line = 8.7, at = -80, adj = 0, cex = cexmy)

  nrisk <- summary(fits, seqtime, extend = T)
  nrisk2 <- summary(fits2[1:2], seqtime, extend = T)
  nriskboth <- bind_cols(
    levs = c(nrisk$strata, nrisk2$strata),
    nrisk = c(nrisk$n.risk, nrisk2$n.risk)
  ) %>%
    mutate(
      levs2 = sub(".*_cat\\=", "", levs),
      levs2 = sub(".*_cat2\\=", "", levs2)
    )

  axis(1,
    at = seqtime, labels = nriskboth$nrisk[nriskboth$levs2 == levs2$levs[1]],
    line = 3.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seqtime, labels = nriskboth$nrisk[nriskboth$levs2 == levs2$levs[2]],
    line = 4.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seqtime, labels = nriskboth$nrisk[nriskboth$levs2 == levs2$levs[3]],
    line = 5.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seqtime, labels = nriskboth$nrisk[nriskboth$levs2 == levs2$levs[4]],
    line = 6.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seqtime, labels = nriskboth$nrisk[nriskboth$levs2 == levs2$levs[5]],
    line = 7.7, tick = FALSE, cex.axis = cexmy
  )
}
```

```{r km, cache = cacheon, dependson="kmfunc", fig.cap = "Cumulative incidence curves EF groups", fig.show='hold', out.width="50%", fig.subcap=c('All-cause mortality', 'CVD', 'CVD/First HFH', 'First HFH'), fig.ncol=2}

kmfunc(
  time = "outtime_death", event = "out_death",
  eventname = "All-cause mortality",
  ymax = 0.3
)

kmfunc(
  time = "outtime_death", event = "out_deathcv",
  eventname = "CVD",
  ymax = 0.3
)

kmfunc(
  time = "outtime_hosphf", event = "out_deathcvhosphf",
  eventname = "CVD/First HFH",
  ymax = 0.3
)

kmfunc(
  time = "outtime_hosphf", event = "out_hosphf",
  eventname = "First HF hospitalisation",
  ymax = 0.3
)
```

```{r km2func, cache=cacheon}
km2func <- function(time, event, eventname, stratavar, ymax = 1) {
  fits <- survfit(formula(paste0("Surv(", time, ",", event, "== 1) ~ ", stratavar)),
    data = pdata %>% filter(survpop)
  )
  ## cox
  smod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "== 1) ~ ", stratavar)),
    data = pdata %>% filter(survpop)
  ))

  hrprint <- paste0(
    fn(smod$conf.int[1, 1], dig = 2),
    " (", fn(smod$conf.int[1, 3], dig = 2),
    "-", fn(smod$conf.int[1, 4], dig = 2), "), ",
    fn(smod$coef[1, 5], dig = 3, p = TRUE)
  )

  # c(bottom, left, top, right)
  cexmy <- 1.2
  par(mar = c(6.75, 8.75, 1, 1.5) + 0.1)

  plots <- plot(fits,
    fun = "event",
    ylab = paste0(eventname, " (%)"),
    yscale = 100,
    xscale = 30,
    col = global_cols[c(1, 2)],
    mark.time = FALSE,
    bty = "n",
    xlim = c(0, 30 * 12),
    ylim = c(0, ymax + 0.05),
    xlab = "Follow-up (months)",
    cex.lab = cexmy,
    axes = F,
    lwd = 2,
    lty = 1,
    xaxs = "i", yaxs = "i"
  )

  axis(2, seq(0, ymax + 0.05, 0.05), c(seq(0, ymax * 100, 5), 100), las = 2, cex.axis = cexmy)
  plotrix::axis.break(2, ymax + 0.025, style = "slash")

  seqtime <- seq(0, 12, 2) * 30
  axis(1, at = seqtime, seq(0, 12, 2), cex.axis = cexmy)

  levs <- levels(pdata %>% pull(!!sym(stratavar)))
  levsprint <- str_replace_all(levs, "%", " digit")

  legend(
    x = 0.5, y = ymax + 0.05, bty = "n", c("", levsprint),
    col = c("white", global_cols[c(1, 2)]), cex = cexmy, lwd = 2, lty = c(1, 1, 1),
    text.col = c("white", global_cols[c(1, 2)])
  )
  legend(
    x = 6 * 30, y = ymax + 0.05, c("HR (95% CI), p-value", "ref", hrprint),
    cex = cexmy, adj = 0.5, bty = "n"
  )

  mtext("No. at risk", side = 1, line = 3.7, at = -105, adj = 0, cex = cexmy, font = 2)
  mtext(levsprint[1], side = 1, line = 4.7, at = -105, adj = 0, cex = cexmy)
  mtext(levsprint[2], side = 1, line = 5.7, at = -105, adj = 0, cex = cexmy)

  nrisk <- summary(fits, seqtime, extend = T)

  axis(1,
    at = seqtime, labels = nrisk$n.risk[nrisk$strata == paste0(stratavar, "=", levs[1])],
    line = 3.7, tick = FALSE, cex.axis = cexmy
  )
  axis(1,
    at = seqtime, labels = nrisk$n.risk[nrisk$strata == paste0(stratavar, "=", levs[2])],
    line = 4.7, tick = FALSE, cex.axis = cexmy
  )
}
```

```{r kmmiss, cache = cacheon, dependson="km2func", fig.cap = "Cumulative incidence curves EF missing", fig.show='hold', out.width="50%", fig.subcap=c('All-cause mortality', 'CVD', 'CVD/First HFH', 'First HFH'), fig.ncol=2}

km2func(
  stratavar = "num_Ef_missing",
  time = "outtime_death", event = "out_death",
  eventname = "All-cause mortality",
  ymax = 0.3
)

km2func(
  stratavar = "num_Ef_missing",
  time = "outtime_death", event = "out_deathcv",
  eventname = "CVD",
  ymax = 0.3
)

km2func(
  stratavar = "num_Ef_missing",
  time = "outtime_hosphf", event = "out_deathcvhosphf",
  eventname = "CVD/First HFH",
  ymax = 0.3
)

km2func(
  stratavar = "num_Ef_missing",
  time = "outtime_hosphf", event = "out_hosphf",
  eventname = "First HF hospitalisation",
  ymax = 0.3
)
```

```{r kmdig, cache = cacheon, dependson="km2func", fig.cap = "Cumulative incidence curves digit bias", fig.show='hold', out.width="50%", fig.subcap=c('All-cause mortality', 'CVD', 'CVD/First HFH', 'First HFH'), fig.ncol=2}

km2func(
  stratavar = "num_Ef_05cat",
  time = "outtime_death", event = "out_death",
  eventname = "All-cause mortality",
  ymax = 0.3
)

km2func(
  stratavar = "num_Ef_05cat",
  time = "outtime_death", event = "out_deathcv",
  eventname = "CVD",
  ymax = 0.3
)

km2func(
  stratavar = "num_Ef_05cat",
  time = "outtime_hosphf", event = "out_deathcvhosphf",
  eventname = "CVD/First HFH",
  ymax = 0.3
)

km2func(
  stratavar = "num_Ef_05cat",
  time = "outtime_hosphf", event = "out_hosphf",
  eventname = "First HF hospitalisation",
  ymax = 0.3
)
```
